runtime: python312
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: 0.65

handlers:
  - url: /static
    static_dir: static
    secure: always
  
  - url: /.*
    script: auto
    secure: always